
const Constants={

    ServiceProviderDashboard: {
     Bankingheader: "Banking",
     BankingParagraph: "You can send your money to one or more payout methods. To manage your payout method(s) or assign a taxpayer, use the edit menu next to each payout method",    
     TotalBalance: "Total Balance",
     LastPayment: "Last Payment:"
    },
    Authentication:{
        Getstarted:"Get started with SwiftBel",
        continue:'Continue',
        Login:'Login',
        haveanaccount:'Already have an account?',
        Signupwith:'Sign up with',
        BytappingCreateanAccount:'By tapping Create an Account or Log In, I agree to SwiftBel’s ',
        TermsofService:'Terms of Service, ',
        PaymentsTermsofService:'Payments Terms of Service ',
        And:'and ',
        NondiscriminationPolicy:'Nondiscrimination Policy ',
        acknowledge:'and acknowledge the ',
        PrivacyPolicy:'Privacy Policy.',
        emailforregistration:'Use an email for registration:',
        Next:'Next',
        Verifyyouremail:'Verify your email',
        EmailSent:'You’re almost there! We sent an email to ',
        EmailtoComplete:'Just click on the link in that email to complete your Sign Up. If you don’t see it, you may need to ',
        SpamFolder:'check your spam folder.',
        cantfindtheemail:'Still can’t find the email?',
        needHelp:'Need help? ',
        ContactUs:'Contact Us',
        ResendEmail:'Resend Email',
        SetUpPassword:'Set Up a Password:',
        TypePassword:'Type a Password here',
        passwordConfirmation:'Confirm your Password here',
        Passwordweak:'Password strength: weak',
        Cantcontainemailaddress:`Can't contain your name or email address`,
        Atleastcharacters:'At least 8 characters with one upper case',
        Containssymbol:'Contains a number and symbol',
        Passwordgood:'Password strength: good',
        Passwordnotmatching:'Password is not matching',
        Welcometo:'Welcome to',
        signUp:'Signup',
        Donthaveanaccount:'Don’t have an account?',
        LogInwith:'Log In with',
        LoginwithMail:"Log in with Mail:",
        password:'Password',
        Createacompanysteps:'Create a company profile in 5 steps',
        Letsdoit:'Let’s do it'
    },
    profile:{
        TellUsanameofyourCompany:'Tell Us a name of your Company',
        Businessname:'Business name *',
        BusinessNumber:'Business Number * ',
        companylocated:'Where is your company located?',
        back:'Back',
        Dragpin:'Drag the map to reposition the pin',
        uploadDoc:'Upload an incorporation document*',
        addPicture:'Add your main profile picture',
        Supprotedformats:'Supproted formats',
        format:'PNG,JPG,PDF',
        FileSize:'File Size',
        maxSize:'Max 5 MB',
        firstName:'First Name',
        lastName:'Last Name',
        AddMoreOwner:'+ Add More Owners',
        BirthProvinceState:'Birth Province State',
        BirthCountry:'Birth Country',
        BirthCity:'Birth City',
        Country:'Country',
        Address:'Address',
        ProvinceState :'Province State',
        City:'City',
        PhotooftheID:'Photo of the ID'
    },
    TYPE:{
        registerMail:'REGISTER_MAIL' ,
        registerId:'REGISTER_ID',
        LoginMail:'LOGIN_MAIL',
        createProfile:'CREATE_PROFILE',
        mobileNumber:'MOBILE_NUMBER',
        addService:'ADD_SERVICE',
        addPicture:'ADD_PICTURE',
        addOwner:'ADD_OWNER',
        Businessname:'BUSINESS_NAME',
        addlocation:'ADD_LOCATION',
        authToken:'AUTH_TOKEN',
        address:'ADDRESS',
        profileToken:'PROFILE_TOKEN',
        PostData:'POST_DATA',
        profileDetails:'PROFILE_DETAILS',
        bannerDetails:'BANNER_DETAILS',
        licenseType:'LICENSE_TYPE'
    }
}
export default Constants;